version: "3.9"
services:
  seq:
    # SeQ is a framework for logging of exceptions etc
    container_name: SeQ_1
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 8081:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/lib/docker/data/jenkins_configuration:/var/jenkins_home
      - /var/lib/docker/data/docker.sock:/var/run/docker.sock