global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'reviewservice'
    metrics_path: /health
    static_configs:
      - targets: ['reviewservice:8080']  # Use the container's internal port
